FROM pytorch/pytorch:2.0.0-cuda11.7-cudnn8-runtime

# Install system dependencies
RUN apt-get update && apt-get install -y ffmpeg git

# Install Python dependencies
RUN pip install transformers datasets librosa soundfile scipy fastapi uvicorn python-multipart

# Set up working directory
WORKDIR /

RUN pip install --no-cache-dir runpod
# Copy the application code to the working directory
COPY rp_handler.py /
COPY load_model.py /

RUN python /load_model.py
# # Pre-download the model (optional but speeds up cold starts)
# RUN python -c "from transformers import WhisperProcessor, WhisperForConditionalGeneration; \
#     processor = WhisperProcessor.from_pretrained('Lingua-Connect/whisper-small-sw-bible'); \
#     model = WhisperForConditionalGeneration.from_pretrained('Lingua-Connect/whisper-small-sw-bible')"

EXPOSE 8000

CMD ["python3", "-u", "rp_handler.py"]